### ISSUE TITLE
Error with font family on IOS

### ISSUE THREAD

**Issue by iRoachie** [hectahertz/react-native-material-dialog#1]
![simulator screen shot apr 4 2017 3 22 26 pm](https://cloud.githubusercontent.com/assets/5962998/24674773/b708f2ec-194a-11e7-9e9c-aef03495fb0b.png)

**Comment by hectahertz** [comment]
Thanks for reporting it!

I'll try to make it also work for iOS this week

**Comment by iRoachie** [comment]
@hectahertz submitted a pr that fixes
