### ISSUE TITLE
Footer cut off on SinglePickerMaterialDialog

### ISSUE THREAD

**Issue by nickbreaton** [hectahertz/react-native-material-dialog#13]
Hey this package is awesome! Thanks for the hard work. 

I ran into an issue when the `scrolled` attribute is added to `SinglePickerMaterialDialog`, and there are enough items to scroll, then the footer is slightly cut off. I can't imagine this is every device, but I tested both on the Galaxy 6S and the Nexus 5X.

| OK - Not Enough Items to Scroll | Bug - Enough Items to Scroll |
|-----|----|
| ![OK - Not Enough Items to Scroll](http://i.imgur.com/9yUXukZ.png)   | ![Bug - Enough Items to Scroll](http://i.imgur.com/wF1o99n.png) |

Please let me know if I can provide more details. Thanks again.

__Edit:__ I was also able to reproduce on both devices with the code provided in the [example](https://github.com/hectahertz/react-native-material-dialog/tree/master/example).
__Edit:__ Does work on iOS.

**Comment by hectahertz** [comment]
Hi @nickbreaton ! thanks for the report :)

It should be fixed now, let me know if it's still reproducible in 0.4.3.

**Comment by nickbreaton** [comment]
Looks good to me! Thanks for the fix. 👍

**Comment by dlehdanakf** [comment]
Still, I have same problem, and it doesn't fixed.
Can anyone tell me how to fix it?

<img width="515" alt="2017-08-02 1 52 35" src="https://user-images.githubusercontent.com/12992959/28858194-de90ad76-7789-11e7-9640-06b07d0f6e82.png">

**Comment by joyceljy** [comment]
@dlehdanakf  try to set scrolled={true}

**Comment by ganeshcse12** [comment]
Still, I have same problem.

**Material dialog version: 0.7.6**

`<SinglePickerMaterialDialog
            title={'My title'}
            okLabel={'Ok'}
            cancelLabel={'Cancel'}
            scrolled={true}
            colorAccent='#12A7BB'
            items={
              this.state.multipleMeetingRoomList.map((multipleMeetingRoom) =>
               ({ value: multipleMeetingRoom.uniqueId, label: multipleMeetingRoom.displayName }))}
            visible={this.state.singlePickerVisible}
            onCancel={() => this.setState({ singlePickerVisible: false })}
            onOk={result => {
              this.setState({ singlePickerVisible: false });
              console.warn('result.selectedItem'+JSON.stringify(result));
            }}
          />`
I have taken a screenshot in landscape mode, can anyone help me to solve this.

<img width="904" alt="Screenshot 2019-07-16 at 6 28 45 PM" src="https://user-images.githubusercontent.com/15715324/61296798-7c42ee80-a7f8-11e9-8ba5-9df173ab0d98.png">
