### ISSUE TITLE
Bug on not selectedIndex press ok

### ISSUE THREAD

**Issue by Angelk90** [hectahertz/react-native-material-dialog#16]
If no item is selected, then press the ok key, the app restarts every time.
One possible solution could be that in:
```
   OnOk = {() => this.props.onOk ({
           SelectedItem: this
           .state
           .Rows [this.state.selectedIndex]
         })}
```
You must check the value of this.state.selectedIndex
guy:
```
  onOk={() =>
if(this.state.selectedIndex ) != undefined) 
 this.props.onOk({
          selectedItem: this
          .state
          .rows[this.state.selectedIndex],
        }))}

```
He could not try it again.

**Comment by hectahertz** [comment]
For a radio button a value should always be selected, and being a controlled component I'd rather leave this logic out of here, feel free to reopen to discuss further about this!
