### ISSUE TITLE
Can't save selected items after press Ok in MultiPickerMaterialDialog

### ISSUE THREAD

**Issue by bphsuan** [hectahertz/react-native-material-dialog#23]
I define state={ seleted:false,selectitems:[] } 
` 
<MultiPickerMaterialDialog
                    title={'選擇要顯示的數據'}
                    titleColor={'#555555'}
                    items={LIST.map((row, index) => {
                        return {value: index, label: row}
                      })}
                    visible={this.state.select}
                    selectedItems={this.state.selectitems}
                    okLabel={'確定'}
                    scrolled={true}
                    cancelLabel={'取消'}
                    onCancel={() => this.setState({ select: false })}
                    onOk={(result) => {
                      this.setState({ select: false });
                      this.setState({ selectitems: result.selectedItems });
                      console.log(this.state.selectitems)
                    }}/>`
,and const array LIST 
just the same as the example doc
But selectitems are still empty after I press OK button
Is there anything wrong?? Hope someone could help me,thanks :'((

**Comment by hectahertz** [comment]
Hi,

I checked your code and I can't see anything wrong just by looking at it, so it's probably something else. Try debugging the `result` variable of the `onOk` prop to check if the component is sending the selected items properly.

If you can't seem to find the problem, I'd advise you to just start from the working MultiPicker code from the examples folder, and modify it to fit your case.

Thanks for using the library!

**Comment by bphsuan** [comment]
Okay,thanks：）
