### ISSUE TITLE
 _reactNative.Platform.select is not a function

### ISSUE THREAD

**Issue by 12343954** [hectahertz/react-native-material-dialog#25]
![image](https://user-images.githubusercontent.com/1804003/31001795-f7327370-a518-11e7-9868-5b685888abdc.png)
![image](https://user-images.githubusercontent.com/1804003/31001844-39b6093c-a519-11e7-8a52-09e9f40a1c30.png)

**Comment by hectahertz** [comment]
Hi! This is probably cause by the old version of react native that you're using, please try to upgrade it as I can't support it.

Thanks and sorry!
