### ISSUE TITLE
One button response

### ISSUE THREAD

**Issue by Georgevik** [hectahertz/react-native-material-dialog#26]
Is there some way to build a dialog with only one response button?

**Comment by sathishjobs** [comment]
How to change fontfamily for action labels..

**Comment by hectahertz** [comment]
Hi @Georgevik, this is not recommended by the [Material Design guidelines](https://material.io/guidelines/components/dialogs.html) (see the `No explicit cancel button` section)

It it's a bad UX practice as you can also press the back button or click outside the dialog to close it.
