### ISSUE TITLE
Alert dialog with image, title and description

### ISSUE THREAD

**Issue by webdevsyd** [hectahertz/react-native-material-dialog#30]
Hi @hectahertz 

Is there a way thatI can put the title below the image, currently when I create a custom content for the dialog box the title appears on top of the dialog

![screen shot 2018-01-07 at 11 55 35 pm](https://user-images.githubusercontent.com/15810023/34651092-49597d74-f406-11e7-88bd-010f547e36f5.png)

If I put a description text below the title this is what I'm getting:
![screen shot 2018-01-08 at 12 31 59 am](https://user-images.githubusercontent.com/15810023/34656032-6df8dcb8-f44e-11e7-923d-363233be7435.png)

Is there a way how can I do this?

![screen shot 2018-01-07 at 11 54 26 pm](https://user-images.githubusercontent.com/15810023/34651094-51152a86-f406-11e7-8fc1-5cb11e9340ee.png)

Also te alert dialog seems have a fix height, because if I have a long text content its like getting an overflow: hidden

**Comment by hectahertz** [comment]
Hi @webdevsyd! 👋🏻

For the title underneath the picture, as it's not part of the Google spec I'd rather leave it out of the library, but you should be able to do it by not setting a title and just including it in the children.

As per the overflow I can't think of a reason why that would happen, if you want to [post a snack](https://snack.expo.io/) I can take a look 😄

**Comment by webdevsyd** [comment]
Hi @hectahertz Finally get to do the UI that I want :D
<img width="272" alt="screen shot 2018-01-08 at 8 43 36 pm" src="https://user-images.githubusercontent.com/15810023/34671230-b06fa066-f4b4-11e7-9e69-de7603a04698.png">
