### ISSUE TITLE
how to change the font size of ok and cancel button?

### ISSUE THREAD

**Issue by longdw** [hectahertz/react-native-material-dialog#31]
how to change the font size of ok and cancel button?
how to hide cancel button that has only one ok button show?

**Comment by hectahertz** [comment]
Hi @longdw,

Hiding the cancel button is not recommended by the [Material Design guidelines](https://material.io/guidelines/components/dialogs.html) (see the `No explicit cancel button` section)

It's not considered a good UX practice as you can also press the back button or click outside the dialog to close it.

As per the font size, it's not supported as this library just follows the [Material Design guidelines](https://material.io/guidelines/components/dialogs.html).

**Comment by peacechen** [comment]
@hectahertz 
There are cases where only a single button is needed.  For example, my app pops up a dialog to notify the user if the internet connection has dropped.  The only button needed is an acknowledgement.

Indeed, Google's Material Design guidelines state the same thing about acknowledgement actions.

> Acknowledgement actions
> When user acknowledgement is required to proceed, a single action may be presented. Alternatively, use a snackbar to communicate this type of information.
> 

https://material.io/design/components/dialogs.html#actions
