### ISSUE TITLE
Default value of the list

### ISSUE THREAD

**Issue by Angelk90** [hectahertz/react-native-material-dialog#32]
@hectahertz : 
Hi, I would need to set a default list value.
I talk about the first start, without the user doing anything.
How can I do?

**Comment by hectahertz** [comment]
Hi @Angelk90 👋🏻

The picker dialogs act as controlled components, so you can set that value in the `selectedItem` or `selectedItems` properties at the point in your code where you need that.

You can read a more about how that pattern works here: https://lorenstewart.me/2016/10/31/react-js-forms-controlled-components/

I hope that's useful!

**Comment by Angelk90** [comment]
@hectahertz : I understood this, but the problem is, consider that I wanted to set a default value.
The value that contains selectedItem is a compound object, I think something like this: {value: '', label: "}
So to set a default value to debbo set an object as the value, this is the only solution?

**Comment by hectahertz** [comment]
Yes, that prop expects the same shape as one of the items of the `items` prop.

There's a brief explanation for the props of all the components [in the readme](https://github.com/hectahertz/react-native-material-dialog/blob/master/README.md) and you can also check their respective propTypes.
