### ISSUE TITLE
Buttons aren't displayed

### ISSUE THREAD

**Issue by vevmesteren** [hectahertz/react-native-material-dialog#34]
with onOk and onCancel defined the buttons in dialog aren't displaying.

Content and Title are displaying correctly. 

```
                    < SinglePickerMaterialDialog
                        title={this.props.translate("TEMPLATE.TITLE")}
                        items={this.props.options.map((row, index) => ({value: index, label: row.cost}))}
                        visible={this.state.singlePickerVisible}
                        selectedItem={this.state.selectedTraining}
                        colorAccent={Colors.colors.ui.primaryDark}
                        backgroundColor={Colors.colors.ui.primary}
                        onCancel={() => this.setState({singlePickerVisible: false})}
                        onOk={(result) => {
                            this._select(result)
                        }}
                        />

![image](https://user-images.githubusercontent.com/143454/38277289-e7ddc926-3765-11e8-92b9-7145a02d3148.png)

```

**Comment by vevmesteren** [comment]
Also noticed that refactoring the use of ListView to Flatlist in order, did you have this planned or have you stopped maintaining this?

**Comment by vevmesteren** [comment]
So it turns out it's not that it wasn't unrelated at all. Removing 'children' from the displays the Buttons, will try to reactor to Flatlist and report back here...

**Comment by vevmesteren** [comment]
As for my error it's simply due to the length of the list. Adding scrolled  to a true fixed it.

**Comment by hectahertz** [comment]
Hi @vevmesteren!

I'm not actively working on the project right now, but if you want to open a pull request with that refactor I can review it and merge it (it would be great ☺️).
