### ISSUE TITLE
Avoid Keyboard?

### ISSUE THREAD

**Issue by iRoachie** [hectahertz/react-native-material-dialog#4]
Is there anyway to move the entire modal upwards when the keyboard opens?

For example I have a text input in the dialog, when the keyboard opens the dialog actions get covered.

**Comment by iRoachie** [comment]
![simulator screen shot apr 24 2017 11 07 57 am](https://cloud.githubusercontent.com/assets/5962998/25343866/4e31f2ac-28de-11e7-95f1-08ff6f01895c.png)

**Comment by iRoachie** [comment]
Seems to only affect iOS, android automatically shifts the modal up.
![screen shot 2017-04-24 at 11 23 18 am](https://cloud.githubusercontent.com/assets/5962998/25344564/7bef7bfe-28e0-11e7-8c97-4b88c6724d02.png)

**Comment by hectahertz** [comment]
Hi @iRoachie, which version of RN are you using?

**Comment by iRoachie** [comment]
0.43.1
