### ISSUE TITLE
Typescript definition for MultiPickerMaterialDialog is incorrect

### ISSUE THREAD

**Issue by Ramdambo** [hectahertz/react-native-material-dialog#43]
The `onOk` method on `MultiPickerMaterialDialog` should really take `{ selectedItems: PickerItem[] }`  as an argument. You can see it by looking at the [code examples](https://github.com/hectahertz/react-native-material-dialog/blob/4e2c565f7eae566eb031412705e391421f156c55/example/App.js#L324).

**Comment by hectahertz** [comment]
Fixed in v0.7.5
