### ISSUE TITLE
With many select options action buttons disappear

### ISSUE THREAD

**Issue by SergiOnGit** [hectahertz/react-native-material-dialog#45]
![image](https://user-images.githubusercontent.com/13105977/45838469-d2531c80-bd22-11e8-9964-bfc157d5bd07.png)

**Comment by alcristog** [comment]
I solved this by setting to 'true' the 'scrolled' property. 

Example:

`<MultiPickerMaterialDialog
          ...
          scrolled={true}
...
        />`

**Comment by SergiOnGit** [comment]
It worked! Thanks
