### ISSUE TITLE
Compatibility with React Native 0.44.0?

### ISSUE THREAD

**Issue by ss44** [hectahertz/react-native-material-dialog#9]
Having trouble using this module with RN-0.44.0.

To Reproduce:

updated examples/package.json modules to:

 "react": "^16.0.0-alpha.6",
 "react-native": "0.44.0",
 "react-native-vector-icons": "^4.1.1"

```bash
rm -rf node_modules && npm install
react-native run-android
```

Error: 

    error: bundling: UnableToResolveError: Unable to resolve module `react/lib/ReactPropTypes`

**Comment by ss44** [comment]
didn't run into this error in subsequent tests. will close for now.

**Comment by hectahertz** [comment]
Happened to me as well when upgrading the example project, I think it's related to https://github.com/facebook/react-native/issues/4968

If you rebuild the project from scratch after upgrading it seems to work
